# 天气
weather:
  key: eba9c707b9d02952e51ae3243fd8d452
  city: 320114
  url: https://restapi.amap.com/v3/weather/weatherInfo?key=${weather.key}&city=${weather.city}&extensions=all

# server酱
server:
  sendKey: SCT78623Trf7qDygXpJPCb1XV7TbpCFjM
  sendUrl: https://sctapi.ftqq.com/${server.sendKey}.send
  openId: KouShaoDi|QiJiu
  testOpenId: KouShaoDi

life:
  key: S5MuMEHelx7U-P7az
  location: nanjing
  lifeUrl: https://api.seniverse.com/v3/life/suggestion.json?key=${life.key}&location=${life.location}